### ISSUE TITLE
[BUG] Like the previous issue with a special character, but this time, the album has a single quote in it, and it confuses the program

### ISSUE THREAD

**Issue by k-quiroz** [DJDoubleD/QobuzDownloaderX-MOD#12]
Tried to download an album with a single quote ( ' ) in its name. In this case, I tried to download hololive meets DJ'TEKINA//SOMETHING remix, and it shows an error. I think it can't find the path because of the single quote.
![image](https://user-images.githubusercontent.com/66580917/232550182-c913e776-7d29-466a-aca2-7645ee64ccd4.png)

**Comment by DJDoubleD** [comment]
The single quote isn't the problem, that's a valid character to use in a folder name.  
The problem is an unlucky and unforeseen circumstance:  

The default "max file name length" is set to 36, which I'm guessing was left on the default value.
Trimming the album name to remove trailing spaces was done before truncating the album name to fit the selected max length.
It just so happens that when you trim `hololive meets DJ'TEKINA//SOMETHING remix` down to 36 characters, you get  `hololive meets DJ'TEKINA//SOMETHING ` => a new path string _**with**_ trailing space...

I will fix this in a next release by making sure that a trimmed down path string can never return a value with a trailing space. But a simple workaround while you wait is increasing the max file name length setting. This is probably what you want anyway to get the full album title in the path.
