### ISSUE TITLE
[Bug] invalid or missing app-id parameter

### ISSUE THREAD

**Issue by Lixumos** [DJDoubleD/QobuzDownloaderX-MOD#14]
# **🐞 Bug Report**

## **Describe the bug**

We have an issue with some users getting the following error log:

```
Failed API request: 
X-App-Id: 950096963, 950096963
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
}
Api response code: 400
Api response status: error
Api response reason: Invalid or missing app_id parameter. (Root=1-6440e2f3-2ad75ae7400cff52649eb895)
```

Apparently it sends the app-id twice and that's why it fails. It accepts the id and token (removed) because it will return 401 then. Like:

```
Failed API request: 
  X-App-Id: 950096963
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64; rv:109.0)
  User-Agent: Gecko/20100101
  User-Agent: Firefox/110.0
}
Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination
```

So why does it sends the app-id trice and thereby making it invalid? Is this something you can look into?

---

### **Is this a regression?**

Not sure

---

### **To Reproduce**

1. Just logging in with id and token

---

### **Expected behaviour**

It should login just fine because it accepts the id and token

---

**Comment by Lixumos** [comment]
So after investigating. It seems to be an issue with Wine. Not sure why Wine sends the id twice, but it could be worth looking into so Mac-users can use the software also

**Comment by DJDoubleD** [comment]
The error messages are incomplete, there should be an extra line starting with `Method: GET, RequestUri: 'https://www.qobuz.com/api.json/0.2/`. 
For future reference, leave this line in and just replace the id and token with `<removed>` for privacy so that you get a line like `Method: GET, RequestUri: 'https://www.qobuz.com/api.json/0.2/user/login?user_id=<removed>&user_auth_token=<removed>', Version: 1.1, Content: <null>, Headers:`
This way the maximum amount of info is available about which API call fails.

I assume the 2nd log is from a deliberate failed login attempt (with invalid token) on a windows machine just to compare the resulting error message?
That being said, since I'm not able to test a "Mac using Wine emulator", please ask the people who can to test the attached debug version and report back if this fixes anything.
[QBDLX-MOD_0.9.10.2-debug-14.zip](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/files/11287379/QBDLX-MOD_0.9.10.2-debug-14.zip)

**Comment by Lixumos** [comment]
That seems to work. No error, no log file generated. Logs in perfectly
