### ISSUE TITLE
[Enhancement] Custom location for user.config

### ISSUE THREAD

**Issue by gisturbance** [DJDoubleD/QobuzDownloaderX-MOD#17]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**
The software is already portable, but the `user.config` file resides under `%appdata%`, defeating the purpose of being portable.

---

## **Describe the solution you'd like**
Store the user.config file in the same directory as the executable, or provide a setting to define its location.

---

## **Describe alternatives you've considered**
Maybe a symlink or copying the user.config after every change to your favored destination.

**Comment by DJDoubleD** [comment]
Found a simple solution using [a Portable SettingsProvider](https://github.com/Bluegrams/SettingsProviders).
Since it offers the choice between classic XML or JSON format for the settings file, I'm opting for a JSON file.
After implementation of the change for this issue, the settings will be saved in the **_<AppFolder>/settings/settings.json_** file.
This should make the application completely portable.
