### ISSUE TITLE
[Bug] Empty track artist tag in few releases 

### ISSUE THREAD

**Issue by viviancels** [DJDoubleD/QobuzDownloaderX-MOD#46]
# **🐞 Bug Report**

## **Describe the bug**

No track artist tag:  https://i.postimg.cc/k4XBQCfq/2023-08-18-095844.png

https://www.qobuz.com/gb-en/album/oldtimers-andrew-cash/4250928386892
https://www.qobuz.com/gb-en/album/fortuna-sunlight-project/4251177547249
https://www.qobuz.com/gb-en/album/7-seasons-higher-ep-andrew-cash/4250605311179
https://www.qobuz.com/gb-en/album/all-that-comes-blue-through-the-porthole-andrew-cash/4250928373403
https://www.qobuz.com/gb-en/album/crossover-ep-andrew-cash/4250325395596
https://www.qobuz.com/gb-en/album/lanai-andrew-cash/4250928350114
https://www.qobuz.com/gb-en/album/tempus-fugit-sunlight-project-amax-dj/4250928321961

etc

Only album artist tag presents if checked

**Comment by DJDoubleD** [comment]
It seems Qobuz sometimes uses the tag "Performer" instead of "MainArtist" a role for the track artist(s) in the string of performers:

![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/34967020/12a44145-c79e-4f87-82b4-933456f97616)
vs

![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/34967020/6e8173be-dab7-4eb6-b2b9-030bb06e5413)

I'll need to add this role name to the performers mapping and also foresee a general fallback in case there are other role tags Qobuz uses that I'm not yet aware off.
