### ISSUE TITLE
bottom part cannot be seen on 150% scaling

### ISSUE THREAD

**Issue by AntiSelosAcademy** [DJDoubleD/QobuzDownloaderX-MOD#48]
I have a 1080p laptop with windows 11 that uses 150% scaling and the bottom half gets cut off force it to use fix scaling.

### **Screenshots**
With fix scaling
![Screenshot 2023-08-19 183432](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/141897211/a30305fd-bf36-4d05-845e-621d79bedc8f)
Without Fixed scaling
![Screenshot 2023-08-19 184328](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/141897211/3593aacb-2e7d-42c1-aff9-92b748636c9c)

**Comment by DJDoubleD** [comment]
I don't have a Windows 11 system to test this on, this might be a limitation of the aging Winforms platform.
Windows 10 seems to handle scaling just fine. Is there maybe a possibility to launch the app using compatibility settings on windows 11?

**Comment by AntiSelosAcademy** [comment]
I guess so, windows scaling has so many problems.

![explorer_Q9vAJj0Fb3](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/141897211/a82d205f-8a14-4c39-a601-cc37cefb224b)

I have to uncheck these just for the app to display correctly. And it looks blurry, but usable.

**Comment by DJDoubleD** [comment]
> I guess so, windows scaling has so many problems.
> 
> ![explorer_Q9vAJj0Fb3](https://user-images.githubusercontent.com/141897211/262508821-a82d205f-8a14-4c39-a601-cc37cefb224b.png)
> 
> I have to uncheck these just for the app to display correctly. And it looks blurry, but usable.

Ah, I misunderstood your original question and didn't realize that when you said "use fix scaling", you meant the High DPI setting to "fix scaling" instead of using a fixed scaling percentage of 150%...

This is also far from perfect on Windows 10 as without the High DPI scaling override option checked, the labels get more blurry the higher the scaling is set. But the app seems to keep full functionality.
And when enabling the different options to override the high dpi scaling, the app either doesn't get scaled at all or breaks as soon as the tag settings at the bottom are opened...

I have read up on this some more and it seems pretty clear that, in order to get correct and clear (crisp) scaling on any Windows version, the entire application would basically have to be rewritten.
I'm afraid that's out of scope of this project/repo and you have already pointed out a less then perfect but workable solution.
So I'll have to close this issue.
