### ISSUE TITLE
Wordy release note eats away the screen

### ISSUE THREAD

**Issue by k-quiroz** [DJDoubleD/QobuzDownloaderX-MOD#50]
I'm actually not sure how or where this would count as an issue, but I'm putting it in anyway since it will probably affect some poor soul. When the release note is too big, the "to update" window gets too big and fills the screen.

![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/66580917/d21a6007-4153-4dbe-9a44-4d47e60ca6bf)

Since this blocks the buttons to click, and the Close button is disabled, it gets weird. I know that I can tab away the problem, but still.

**Comment by DJDoubleD** [comment]
Seems like a valid issue to me, although it is of course non-blocking.
My screen seemed to be large enough to not encounter the issue, but it was easily reproduced by forcing a massive block of text in a debug version.

I found simple solution quite fast using a [FlexibleMessageBox](http://www.codeproject.com/Articles/601900/FlexibleMessageBox), so will be fixed in the next release.
The fix will most likely be useful in the future as I like to document my releases as best as possible.
