### ISSUE TITLE
[Enhancement] Fix Incorrect Copyright Metadata

### ISSUE THREAD

**Issue by phantomswiftx** [DJDoubleD/QobuzDownloaderX-MOD#70]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

* I've noticed that the metadata contains incorrect copyright information. For example, the correct copyright for this album should be "© 2017 Apollo A-1 LLC ℗ 2017 Apollo A-1 LLC," but it currently displays "℗ Big Machine Records, LLC." This inconsistency in copyright data affects the accuracy and completeness of the information. 
![This should be the copyright](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/155817902/c792e740-53d0-4f9c-a239-452dfd83503a)
![Screenshot (5)](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/155817902/2b945f2f-bb10-4952-9847-66e9bb9b4048)

---

## **Describe the solution you'd like**

* I suggest updating/fixing to reflect accurate copyright information. Ensuring that the metadata aligns with the official copyright details will enhance the overall accuracy of the application.

**Comment by orbittwz** [comment]
I can't find a detailed evidence but Apollo A-1 LLC purchase the Big Machine Records masters of Taylor's work to distribute it via other platforms, so qobuz probably changed it in the pages...
But if you look just above and in the top of the page it says Big Machine Records LLC.
Fine either way...

**Comment by DJDoubleD** [comment]
The Qobuz API returns a `COPYRIGHT` field for each individual track and I use that field for the track's metadata, not the album's field.
As you can see in the credits of the web player, the `COPYRIGHT` field is correctly written as per the credits for each track:

![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/34967020/3c0f383d-e470-4298-8646-3515e9d08a54)

In fact, I can't even find any mention of `© 2017 Apollo A-1 LLC ℗ 2017 Apollo A-1 LLC,` in the web player's credits for this album anywhere.

Since individual tracks can have different copyright values from the album on which they appear (especially for compilations), this is "works as designed", so I don't really see any reason to change this.
