### ISSUE TITLE
[Bug] Error when downloading some akon albuns/tracks

### ISSUE THREAD

**Issue by ElVallon** [DJDoubleD/QobuzDownloaderX-MOD#79]
# **🐞 Bug Report**

## **Describe the bug**
I made this tool download the Akon discographie available on Qobuz with https://www.qobuz.com/us-en/interpreter/akon/62442 link.

I have USA account.

*

---

### **Is this a regression?**
I don't know if this is a regression, as i started using this tool at version 1.2.5.0.

---

### **To Reproduce**

1] Open the tool;
2] Input your login details and press enter;
3] Input the desired qobuz link ( https://www.qobuz.com/us-en/interpreter/akon/62442 in my case) in the blank field;
4] Press blue download button;
5] Some albuns/tracks will download while others not.

---

### **Expected behaviour**

What i expected to happen is to download Akon's entire discographie available on qobuz;

---

### **Screenshots**
![kZU4YaIWOi](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/163336209/4ec69c23-907f-4025-a642-2ad558da04ce)

---

### **Additional context**
Here are both error logs:
[Download_Errors.log](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/files/14591853/Download_Errors.log)
[Download_Log_2024-03-13_13.46.49.794.log](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/files/14591855/Download_Log_2024-03-13_13.46.49.794.log)

*

**Comment by orbittwz** [comment]
you cannot download an entire discography, the program is not adopted to this kind of request...
please use the search function, search for the artist specific album or single or whatever, and download the one you want...

**Comment by DJDoubleD** [comment]
It is definitely possible to download [artist discographies](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/wiki#artists) and [entire labels](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/wiki#labels), both up to 5000 albums (that's the limit that the API's can return, nothing I can do about that).

Now it is unclear to me if the issue is about albums that were expected to be in the discography and where not downloaded at all i.e. no trace of the app trying to start the album download in the download log (1) or if the issue is about the albums that were included in the uploaded download log but produced errors and were therefore not downloaded (2).

If the issue is about option (1), please give some example albums so I can check if they were included in the album list that the API returns for the artist.
If the issue is about option (2), then the errors `System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'streaming-qobuz-std.akamaized.net'` indicate that there were network issues (possibly on qobuz serverside but more likely on your local network) between `2024-03-13 14:01:10` and `2024-03-13 14:02:45` (your local time).
As long as you didn't change the downloaded folders/files (rename, move, ...), just re-download that same artist url and it will skip the already downloaded tracks/covers and retry the failed items.

**Comment by ElVallon** [comment]
> It is definitely possible to download [artist discographies](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/wiki#artists) and [entire labels](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/wiki#labels), both up to 5000 albums (that's the limit that the API's can return, nothing I can do about that).
> 
> Now it is unclear to me if the issue is about albums that were expected to be in the discography and where not downloaded at all i.e. no trace of the app trying to start the album download in the download log (1) or if the issue is about the albums that were included in the uploaded download log but produced errors and were therefore not downloaded (2).
> 
> If the issue is about option (1), please give some example albums so I can check if they were included in the album list that the API returns for the artist. If the issue is about option (2), then the errors `System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'streaming-qobuz-std.akamaized.net'` indicate that there were network issues (possibly on qobuz serverside but more likely on your local network) between `2024-03-13 14:01:10` and `2024-03-13 14:02:45` (your local time). As long as you didn't change the downloaded folders/files (rename, move, ...), just re-download that same artist url and it will skip the already downloaded tracks/covers and retry the failed items.

Well, i just wanna know what was the exact reason of the download errors: was (1) or (2)?

**Comment by DJDoubleD** [comment]
@ElVallon I think you misunderstood my message, I was asking **_you_** if you were just informing about the error messages or if you had albums that you believe should have been attempted to be downloaded, but that were not mentioned in the log files at all.
Since you specifically ask for the reason of the _errors_ in your follow-up message, I'm going to assume you were talking about what I described as option 2.

As I said in my previous message, the error messages are pretty clear and all of them happend consecutively between `2024-03-13 14:01:10` and `2024-03-13 14:02:45`.
The messages clearly state that during that minute and a half, your PC could not find (resolve) the IP address of the server `streaming-qobuz-std.akamaized.net`.

There is absolutely no way for me to figure out what _exactly_ was happening with your PC, LAN or internet connection during that period, but simply put: your connection became unstable for 95 seconds, all downloads that were attempted during that timeframe failed, then your PC's connection recovered and all downloads after that period seem to have succeeded.

Just retry the download and it will most likely succeed in getting the missed albums/tracks.

**Comment by ElVallon** [comment]
> @ElVallon I think you misunderstood my message, I was asking **_you_** if you were just informing about the error messages or if you had albums that you believe should have been attempted to be downloaded, but that were not mentioned in the log files at all. Since you specifically ask for the reason of the _errors_ in your follow-up message, I'm going to assume you were talking about what I described as option 2.
> 
> As I said in my previous message, the error messages are pretty clear and all of them happend consecutively between `2024-03-13 14:01:10` and `2024-03-13 14:02:45`. The messages clearly state that during that minute and a half, your PC could not find (resolve) the IP address of the server `streaming-qobuz-std.akamaized.net`.
> 
> There is absolutely no way for me to figure out what _exactly_ was happening with your PC, LAN or internet connection during that period, but simply put: your connection became unstable for 95 seconds, all downloads that were attempted during that timeframe failed, then your PC's connection recovered and all downloads after that period seem to have succeeded.
> 
> Just retry the download and it will most likely succeed in getting the missed albums/tracks.

"if you were just informing about the error messages" : oh yeah, i'm informing about such errors while asking about what did happen.

"The messages clearly state that during that minute and a half, your PC could not find (resolve) the IP address of the server": Oh, ok! Good to know that the reason was only that!

Thanks for the clarifications! =]
