### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by viviancels** [DJDoubleD/QobuzDownloaderX-MOD#85]
# **🐞 Bug Report**

## **Describe the bug**
Hello all. Recently, some tracks have not been downloaded in QobuzDownloaderXMod 1.2.5.0, the speed drops to zero, tracks are downloaded from 2-3 attempts. The red Stop button does not work.

I think, maybe this is issue Qobuz itself?

This applies to specific releases. Example:
Trying to download release 1 failed.
The second attempt to download release 1 was a failure.
The third attempt to download release 1 failed.
Trying to download another release is a success.
The fourth attempt to download release 1 failed.
After some time, release 1 is downloaded successfully.

UPD: I was told that if the release is not downloaded by copying the link to the album into the [QobuzDownloaderX-MOD](https://github.com/DJDoubleD/QobuzDownloaderX-MOD), you can find the release by searching for the [QobuzDownloaderX-MOD](https://github.com/DJDoubleD/QobuzDownloaderX-MOD) and download it this way.

Screenshot:
https://i.postimg.cc/x1GtZrDh/2024-04-29-190127.png

**Comment by DJDoubleD** [comment]
@viviancels could you please add the url of the release/album for which you experienced this issue and also note what the counrty of the account is that you used?

At first glance, this really seems like a networking/connection issue, but I'll try to reproduce the issue if you provide this additional info.
Could you  say if you used a VPN or not, as this could also play a role.

**Comment by viviancels** [comment]
https://www.qobuz.com/gb-en/album/city-of-tears-zhiroc/evp44s9gttcwa
Country: Canada
Minute ago I tried again and release downloaded well by pasting url on high speed. When there was a glitch few hours ago, I checked my internet, the speed was 500 megabits

**Comment by DJDoubleD** [comment]
I have tried to reproduce the issue in multiple configurations (with VPN, without VPN, different countries, ...) and the release just downloads every time at high speeds.
Given the fact than you were also able to download it at high speed at a different time, strongly indicates that the issue was a temporary internet connectivity problem.

Please keep in mind that a speedtest doesn't always reflect the speed you will get from each website/service.
It seems likely that you experienced a temporary connectivity issue with the content providing server from Qobuz (different released can be served from different servers) and this issue is not related to the QBDLX-MOD application.

Therefore, I'm closing the issue.
